version: '3.9'

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: twitter-clone
    ports:
      - 5432:5432
    volumes:
      - ./pgdata:/var/lib/postgresql/data
